version: '3.6'

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_AUTHENTICATION_ENABLED=false
    command: bin/pulsar standalone