version: '3.6'

services:
  pulsar:
    networks:
      - cameltrace
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_AUTHENTICATION_ENABLED=false
    command: bin/pulsar standalone

  jaeger:
    networks:
      - cameltrace
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16685:16685"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"

  otel_collector:
    networks:
      - cameltrace
    image: otel/opentelemetry-collector-contrib:0.120.0
    volumes:
      - ./camel/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # otlp receiver grpc
      - "4318:4318"   # otlp receiver http
      - "55679:55679" # zpages extension

#  datadog:
#    image: datadog/agent:7.44.1
#    environment:
#      - DD_API_KEY=
#      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
#      - DD_APM_ENABLED=true
#      - DD_OTLP_CONFIG_TRACES_ENABLED=true
#      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=localhost:4317
#      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=localhost:4318
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /proc/:/host/proc/:ro
#      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
#    ports:
#      - "4317:4317"
#      - "8126:8126"
#      - "8125:8125"

networks:
  cameltrace: