version: '3.6'

services:
  pulsar:
    networks:
      - cameltrace
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_AUTHENTICATION_ENABLED=false
    command: bin/pulsar standalone

  jaeger:
    networks:
      - cameltrace
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"

  otel_collector:
    networks:
      - cameltrace
    image: otel/opentelemetry-collector-contrib:0.85.0
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

networks:
  cameltrace: